services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
    ports:
      - "5432:5432"
    volumes:
      - restaurant-postgres-data:/var/lib/postgresql/data

volumes:
  restaurant-postgres-data:
